//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASFW_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASFW_USER()
        {
            this.ASFW_ACTIVESESSION = new HashSet<ASFW_ACTIVESESSION>();
        }
    
        public int USERID { get; set; }
        public string DOC_NUMBER { get; set; }
        public string FIRST_NAME { get; set; }
        public string SECOND_NAME { get; set; }
        public string FIRST_LASTNAME { get; set; }
        public string SECOND_LASTNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<long> PROFILEID { get; set; }
        public string USER { get; set; }
        public string PASS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public int COMPANYID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> INTENTS { get; set; }
        public Nullable<System.DateTime> LAST_INTENT { get; set; }
        public string CONFIG_PARMS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASFW_ACTIVESESSION> ASFW_ACTIVESESSION { get; set; }
        public virtual ASFW_COMPANY ASFW_COMPANY { get; set; }
    }
}
