//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASFW_CATTYPE
    {
        public int CATTYPEID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public bool VISIBLE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
