//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASFW_COMPANY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASFW_COMPANY()
        {
            this.ASFW_ACTIVESESSION = new HashSet<ASFW_ACTIVESESSION>();
            this.ASFW_USER = new HashSet<ASFW_USER>();
            this.LGC_RECOLECCION = new HashSet<LGC_RECOLECCION>();
        }
    
        public int COMPANYID { get; set; }
        public string NAME { get; set; }
        public string DOCNUMBER { get; set; }
        public string TELEPHONE { get; set; }
        public string CELLPHONE { get; set; }
        public string ADRESS { get; set; }
        public Nullable<System.Guid> CLIENT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASFW_ACTIVESESSION> ASFW_ACTIVESESSION { get; set; }
        public virtual LGC_CLIENTE LGC_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASFW_USER> ASFW_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGC_RECOLECCION> LGC_RECOLECCION { get; set; }
    }
}
