//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCG_CLIENTE_CLIENTE
    {
        public int C_ClienteID { get; set; }
        public System.Guid ClienteID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual LGC_CLIENTE LGC_CLIENTE { get; set; }
    }
}
