//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGC_RECOLECCION_ITEM
    {
        public long ITEM_ID { get; set; }
        public long RECOLECCION_ID { get; set; }
        public Nullable<int> EAN { get; set; }
        public string DESCRIPCION { get; set; }
        public int CANTIDAD { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    
        public virtual LGC_RECOLECCION LGC_RECOLECCION { get; set; }
    }
}
