//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGC_GUIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LGC_GUIA()
        {
            this.LGC_DESPACHO = new HashSet<LGC_DESPACHO>();
        }
    
        public long GUIA_ID { get; set; }
        public string GUIA_PREFIJO { get; set; }
        public int TIPO_ID { get; set; }
        public Nullable<long> RECOLECCION_ID { get; set; }
        public Nullable<long> DESPACHO_ID { get; set; }
        public int ORIGEN { get; set; }
        public string REMITENTE_NOMBRE { get; set; }
        public string REMITENTE_DIRECCION { get; set; }
        public string REMITENTE_TELEFONO { get; set; }
        public int DESTINO { get; set; }
        public string DESTINATARIO_NOMBRE { get; set; }
        public string DESTINATARIO_DIRECCION { get; set; }
        public string DESTINATARIO_TELEFONO { get; set; }
        public System.DateTime FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public int UNIDADES { get; set; }
        public int PESO { get; set; }
        public int PESO_VOL { get; set; }
        public int PESO_LIQ { get; set; }
        public Nullable<decimal> VALOR_DECLARADO { get; set; }
        public string DICE_CONTENER { get; set; }
        public int ELABORADO_POR { get; set; }
        public Nullable<int> ENCARGADO_A { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> PROVEEDOR_ID { get; set; }
        public string PROVEEDOR_GUIA_NO { get; set; }
    
        public virtual ASFW_USER ASFW_USER { get; set; }
        public virtual ASFW_USER ASFW_USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGC_DESPACHO> LGC_DESPACHO { get; set; }
        public virtual LGC_DESPACHO LGC_DESPACHO1 { get; set; }
        public virtual LGC_RECOLECCION LGC_RECOLECCION { get; set; }
    }
}
