//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGC_CLIENTE_PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LGC_CLIENTE_PROVEEDORES()
        {
            this.LGC_RECOLECCION = new HashSet<LGC_RECOLECCION>();
            this.LGC_DESPACHO = new HashSet<LGC_DESPACHO>();
        }
    
        public int PROVEEDOR_ID { get; set; }
        public string NOMBRE { get; set; }
        public string CODIGO { get; set; }
        public string EJECUTIVO { get; set; }
        public string EJECUTIVO_MAIL { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string DIRECCION { get; set; }
        public int CIUDAD { get; set; }
        public System.Guid ClienteID { get; set; }
        public string EXT { get; set; }
    
        public virtual LGC_CLIENTE LGC_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGC_RECOLECCION> LGC_RECOLECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGC_DESPACHO> LGC_DESPACHO { get; set; }
    }
}
