//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ASFW_CITY_CODE_DEP
    {
        public int ID { get; set; }
        public string NOM_DEPTO { get; set; }
        public string COD_DEPTO { get; set; }
    }
}
