//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ASFW_CATVAL
    {
        public int CATVALID { get; set; }
        public int CATTYPEID { get; set; }
        public string VAL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> CATPARENT0 { get; set; }
        public Nullable<int> CATPARENT1 { get; set; }
        public Nullable<decimal> CUSTOMFIELD0 { get; set; }
        public Nullable<decimal> CUSTOMFIELD1 { get; set; }
        public string CUSTOMFIELD2 { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<bool> SHOWABLE { get; set; }
    }
}
