//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ASFW_CITY_CODE_MUN
    {
        public Nullable<int> ID { get; set; }
        public int DEPTO_ID { get; set; }
        public string COD_DEPTO { get; set; }
        public string COD_MUN { get; set; }
        public string NOM_MUN { get; set; }
        public string MUN_DEPTO { get; set; }
        public Nullable<int> ZONA_POSTAL { get; set; }
        public Nullable<int> COD_POSTAL { get; set; }
    }
}
