//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GUIA_ETIQUETA
    {
        public string GUIA_PREFIJO { get; set; }
        public long GUIA_ID { get; set; }
        public string CUIDAD { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string REFERENCIA { get; set; }
        public string CONSECUTIVO_CLIENTE { get; set; }
        public byte[] BARCODE { get; set; }
    }
}
