//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LgcWMS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LGC_DESPACHO_GRID
    {
        public Nullable<long> GUIA_ID { get; set; }
        public Nullable<long> GUIA { get; set; }
        public string CONSECUTIVO_CLIENTE { get; set; }
        public string CONSECUTIVO { get; set; }
        public string CODIGO_PREMIO { get; set; }
        public string PREMIO { get; set; }
        public Nullable<System.DateTime> FECHA_REDENCION { get; set; }
        public int REMITENTE_NOMBRE { get; set; }
        public string REMITENTE_VAL { get; set; }
        public string REMITENTE_DIRECCION { get; set; }
        public Nullable<int> ORIGEN_ID { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINATARIO_NOMBRE { get; set; }
        public string DESTINATARIO_DIRECCION { get; set; }
        public string DESTINATARIO_TELEFONO { get; set; }
        public int DESTINO_ID { get; set; }
        public string DESTINO { get; set; }
        public int UNIDADES { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public string ESPECIFICACIONES { get; set; }
    }
}
